name: 'Pull request labeler'
description: 'Add labels to new pull requests when introducing a new dependency'
author: Keenan Szulik

inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    
  configuration-path:
    description: 'Path for the label configurations'
    default: '.github/labeler.yml'
runs:
  using: 'node12'
  main: 'lib/main.js'
